EDITIONS = {
    "M20": "Core Set 2020",
    "MH1": "Modern Horizons",
    "MPS_WAR": "War of the Spark Mythic Edition",
    "WAR": "War of the Spark",
    "MPS_RNA": "Ravnica Allegiance Mythic Edition",
    "RNA": "Ravnica Allegiance",
    "UMA": "Ultimate Masters",
    "MPS_GRN": "Guilds of Ravnica Mythic Edition",
    "GRN": "Guilds of Ravnica",
    "C18": "Commander 2018",
    "CM2": "Commander Anthology 2018",
    "M19": "Core Set 2019",
    "MTGA": "MTG Arena New Player Experience",
    "BBD": "Battlebond",
    "DOM": "Dominaria",
    "A25": "Masters 25",
    "E02": "Explorers of Ixalan",
    "DDT": "Duel Decks: Merfolk vs. Goblins",
    "UST": "Unstable",
    "IMA": "Iconic Masters",
    "RIX": "Rivals of Ixalan",
    "XLN": "Ixalan",
    "C17": "Commander 2017",
    "CMA": "Commander Anthology",
    "W17": "Welcome Deck 2017",
    "E01": "Archenemy: Nicol Bolas",
    "HOU": "Hour of Devastation",
    "DDS": "Duel Decks: Mind vs. Might",
    "MM3": "Modern Masters 2017 Edition",
    "MPS_AKH": "Masterpiece Series: Amonkhet Invocations",
    "AKH": "Amonkhet",
    "AER": "Aether Revolt",
    "C16": "Commander 2016",
    "CN2": "Conspiracy: Take The Crown",
    "KLD": "Kaladesh",
    "EMA": "Eternal Masters",
    "EMN": "Eldritch Moon",
    "W16": "Welcome Deck 2016",
    "SOI": "Shadows Over Innistrad",
    "OGW": "Oath of the Gatewatch",
    "C15": "Commander 2015",
    "BFZ": "Battle for Zendikar",
    "ORI": "Magic Origins",
    "MM2": "Modern Masters 2015 Edition",
    "DTK": "Dragons of Tarkir",
    "FRF": "Fate Reforged",
    "C14": "Commander 2014",
    "KTK": "Khans of Tarkir",
    "M15": "Magic 2015 Core Set",
    "VMA": "Vintage Masters",
    "CNS": "Conspiracy",
    "JOU": "Journey into Nyx",
    "BNG": "Born of the Gods",
    "C13": "Commander 2013 Edition",
    "THS": "Theros",
    "M14": "Magic 2014 Core Set",
    "MMA": "Modern Masters",
    "DGM": "Dragon's Maze",
    "GTC": "Gatecrash",
    "RTR": "Return to Ravnica",
    "M13": "Magic 2013",
    "AVR": "Avacyn Restored",
    "DKA": "Dark Ascension",
    "ISD": "Innistrad",
    "M12": "Magic 2012",
    "NPH": "New Phyrexia",
    "MBS": "Mirrodin Besieged",
    "SOM": "Scars of Mirrodin",
    "M11": "Magic 2011",
    "ROE": "Rise of the Eldrazi",
    "WWK": "Worldwake",
    "EXP": "Zendikar Expeditions",
    "ZEN": "Zendikar",
    "M10": "Magic 2010",
    "ARB": "Alara Reborn",
    "CON": "Conflux",
    "ALA": "Shards of Alara",
    "EVE": "Eventide",
    "SHM": "Shadowmoor",
    "MOR": "Morningtide",
    "LRW": "Lorwyn",
    "10ED": "Tenth Edition",
    "FUT": "Future Sight",
    "PLC": "Planar Chaos",
    "TSB": 'Time Spiral "Timeshifted"',
    "TSP": "Time Spiral",
    "CSP": "Coldsnap",
    "DIS": "Dissension",
    "GPT": "Guildpact",
    "RAV": "Ravnica: City of Guilds",
    "9ED": "Ninth Edition",
    "SOK": "Saviors of Kamigawa",
    "BOK": "Betrayers of Kamigawa",
    "CHK": "Champions of Kamigawa",
    "UNH": "Unhinged",
    "5DN": "Fifth Dawn",
    "DST": "Darksteel",
    "MRD": "Mirrodin",
    "8ED": "Eighth Edition",
    "SCG": "Scourge",
    "LGN": "Legions",
    "ONS": "Onslaught",
    "JUD": "Judgment",
    "TOR": "Torment",
    "ODY": "Odyssey",
    "7ED": "Seventh Edition",
    "APC": "Apocalypse",
    "PLS": "Planeshift",
    "INV": "Invasion",
    "PCY": "Prophecy",
    "NEM": "Nemesis",
    "MMQ": "Mercadian Masques",
    "6ED": "Classic Sixth Edition",
    "UDS": "Urza's Destiny",
    "ULG": "Urza's Legacy",
    "USG": "Urza's Saga",
    "UGL": "Unglued",
    "EXO": "Exodus",
    "STH": "Stronghold",
    "TMP": "Tempest",
    "5ED": "Fifth Edition",
    "WTH": "Weatherlight",
    "VIS": "Visions",
    "MIR": "Mirage",
    "ALL": "Alliances",
    "HML": "Homelands",
    "ICE": "Ice Age",
    "4ED": "Fourth Edition",
    "CHR": "Chronicles",
    "3ED": "Revised Edition",
    "FEM": "Fallen Empires",
    "DRK": "The Dark",
    "LEG": "Legends",
    "ATQ": "Antiquities",
    "ARN": "Arabian Nights",
    "2ED": "Unlimited Edition",
    "LEB": "Limited Edition Beta",
    "LEA": "Limited Edition Alpha",
    "PAER": "Aether Revolt Promos",
    "PAKH": "Amonkhet Promos",
    "ATH": "Anthologies",
    "ARC": "Archenemy",
    "PBFZ": "Battle for Zendikar Promos",
    "BRB": "Battle Royale Box Set",
    "PBBD": "Battlebond Promos",
    "BTD": "Beatdown Box Set",
    "PSS1": "BFZ Standard Series",
    "CM1": "Commander's Arsenal",
    "PM19": "Core Set 2019 Promos",
    "PM20": "Core Set 2020 Promos",
    "DCI": "DCI Promos",
    "DM": "Deckmasters",
    "PDOM": "Dominaria Promos",
    "PDTK": "Dragons of Tarkir Promos",
    "DD3_DVD": "Duel Decks Anthology, Divine vs. Demonic",
    "DD3_EVG": "Duel Decks Anthology, Elves vs. Goblins",
    "DD3_GVL": "Duel Decks Anthology, Garruk vs. Liliana",
    "DD3_JVC": "Duel Decks Anthology, Jace vs. Chandra",
    "DDH": "Duel Decks: Ajani vs. Nicol Bolas",
    "DDQ": "Duel Decks: Blessed vs. Cursed",
    "DVD": "Duel Decks: Divine vs. Demonic",
    "DDO": "Duel Decks: Elspeth vs. Kiora",
    "DDF": "Duel Decks: Elspeth vs. Tezzeret",
    "EVG": "Duel Decks: Elves vs. Goblins",
    "DDU": "Duel Decks: Elves vs. Inventors",
    "DDD": "Duel Decks: Garruk vs. Liliana",
    "DDL": "Duel Decks: Heroes vs. Monsters",
    "DDJ": "Duel Decks: Izzet vs. Golgari",
    "JVC": "Duel Decks: Jace vs. Chandra",
    "DDM": "Duel Decks: Jace vs. Vraska",
    "DDG": "Duel Decks: Knights vs. Dragons",
    "DDR": "Duel Decks: Nissa vs. Ob Nixilis",
    "DDE": "Duel Decks: Phyrexia vs. the Coalition",
    "DDK": "Duel Decks: Sorin vs. Tibalt",
    "DDN": "Duel Decks: Speed vs. Cunning",
    "DDI": "Duel Decks: Venser vs. Koth",
    "DDP": "Duel Decks: Zendikar vs. Eldrazi",
    "DPA": "Duels of the Planeswalkers",
    "PDP10": "Duels of the Planeswalkers Promos 2010",
    "PDP11": "Duels of the Planeswalkers Promos 2011",
    "PDP12": "Duels of the Planeswalkers Promos 2012",
    "PDP13": "Duels of the Planeswalkers Promos 2013",
    "PDP14": "Duels of the Planeswalkers Promos 2014",
    "PEMN": "Eldritch Moon Promos",
    "PFRF": "Fate Reforged Promos",
    "FBB": "Foreign Black Border",
    "V15": "From the Vault: Angels",
    "V14": "From the Vault: Annihilation (2014)",
    "FVD": "From the Vault: Dragons",
    "V09": "From the Vault: Exiled",
    "V11": "From the Vault: Legends",
    "V16": "From the Vault: Lore",
    "V12": "From the Vault: Realms",
    "V10": "From the Vault: Relics",
    "V17": "From the Vault: Transform",
    "V13": "From the Vault: Twenty",
    "GNT": "Game Night",
    "PG08": "Gateway 2008",
    "G18": "Gift Pack",
    "GS1": "Global Series: Jiang Yanggu and Mu Yanling",
    "PGPX": "Grand Prix Promos",
    "GK2_AZORIU": "Guild Kit: Azorius",
    "GK1_BOROS": "Guild Kit: Boros",
    "GK1_DIMIR": "Guild Kit: Dimir",
    "GK1_GOLGAR": "Guild Kit: Golgari",
    "GK2_GRUUL": "Guild Kit: Gruul",
    "GK1_IZZET": "Guild Kit: Izzet",
    "GK2_ORZHOV": "Guild Kit: Orzhov",
    "GK2_RAKDOS": "Guild Kit: Rakdos",
    "GK1_SELESN": "Guild Kit: Selesnya",
    "GK2_SIMIC": "Guild Kit: Simic",
    "PGRN": "Guilds of Ravnica Promos",
    "HHO": "Happy Holidays",
    "PHJ": "Hobby Japan Promos",
    "PHOU": "Hour of Devastation Promos",
    "PIDW": "IDW Comics 2012",
    "PI13": "IDW Comics 2013",
    "PI14": "IDW Comics 2014",
    "PXLN": "Ixalan Promos",
    "JGP": "Judge Gift Cards 1998",
    "G99": "Judge Gift Cards 1999",
    "G00": "Judge Gift Cards 2000",
    "G01": "Judge Gift Cards 2001",
    "G02": "Judge Gift Cards 2002",
    "G03": "Judge Gift Cards 2003",
    "G04": "Judge Gift Cards 2004",
    "G05": "Judge Gift Cards 2005",
    "G06": "Judge Gift Cards 2006",
    "G07": "Judge Gift Cards 2007",
    "G08": "Judge Gift Cards 2008",
    "G09": "Judge Gift Cards 2009",
    "G10": "Judge Gift Cards 2010",
    "G11": "Judge Gift Cards 2011",
    "J12": "Judge Gift Cards 2012",
    "J13": "Judge Gift Cards 2013",
    "J14": "Judge Gift Cards 2014",
    "J15": "Judge Gift Cards 2015",
    "J16": "Judge Gift Cards 2016",
    "J17": "Judge Gift Cards 2017",
    "J18": "Judge Gift Cards 2018",
    "J19": "Judge Gift Cards 2019",
    "PKLD": "Kaladesh Promos",
    "PKTK": "Khans of Tarkir Promos",
    "PPP1": "M20 Promo Packs",
    "PMEI": "Magazine Inserts",
    "PM12": "Magic 2012 Promos",
    "PRM": "Magic Online Promos",
    "PORI": "Magic Origins Promos",
    "CMD": "Magic: The Gathering-Commander",
    "PF19": "MagicFest 2019",
    "MPS_KLD": "Masterpiece Series: Kaladesh Inventions",
    "MED": "Masters Edition",
    "ME2": "Masters Edition II",
    "ME3": "Masters Edition III",
    "ME4": "Masters Edition IV",
    "MD1": "Modern Event Deck 2014",
    "PMH1": "Modern Horizons Promos",
    "PANA": "MTG Arena Promos",
    "POGW": "Oath of the Gatewatch Promos",
    "HOP": "Planechase",
    "PC2": "Planechase 2012 Edition",
    "PCA": "Planechase Anthology",
    "POR": "Portal",
    "PO2": "Portal Second Age",
    "PTK": "Portal Three Kingdoms",
    "PD2": "Premium Deck Series: Fire and Lightning",
    "PD3": "Premium Deck Series: Graveborn",
    "H09": "Premium Deck Series: Slivers",
    "PPRO": "Pro Tour Promos",
    "PPR": "Promo set for Gatherer",
    "PARC": "Promotional Schemes",
    "PRNA": "Ravnica Allegiance Promos",
    "PRES": "Resale Promos",
    "PRTR": "Return to Ravnica Promos",
    "PROE": "Rise of the Eldrazi Promos",
    "PRIX": "Rivals of Ixalan Promos",
    "PSDC": "San Diego Comic-Con 2013",
    "PS14": "San Diego Comic-Con 2014",
    "PS16": "San Diego Comic-Con 2016",
    "PS17": "San Diego Comic-Con 2017",
    "PS19": "San Diego Comic-Con 2019",
    "PSOI": "Shadows over Innistrad Promos",
    "SS1": "Signature Spellbook: Jace",
    "S99": "Starter 1999",
    "S00": "Starter 2000",
    "TPR": "Tempest Remastered",
    "FRF_UGIN": "Ugin's Fate promos",
    "UMA_BOX": "Ultimate Box Toppers",
    "PURL": "URL/Convention Promos",
    "VAN": "Vanguard",
    "PWAR": "War of the Spark Promos",
    "PWP10": "Wizards Play Network 2010",
    "PWCQ": "World Magic Cup Qualifiers",
    "PWWK": "Worldwake Promos",
    "PXTC": "XLN Treasure Chest",
}
